services:
  - type: web
    name: carpet-bot
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: carpet-db       # This connects to the DB defined below
          property: connectionString
      - key: BOT_TOKEN
        value: "8524797886:AAFel51fCM7KtJAz6KkRchDbJnzjy3uc1B8"  # <--- PASTE YOUR TOKEN HERE
      - key: ADMIN_CHAT_ID
        value: "7829091241"  # <--- PASTE YOUR ADMIN ID HERE

databases:
  - name: carpet-db
    databaseName: carpetdb
    user: carpetuser